### ISSUE TITLE
Possibilité de "surveiller" une publi

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/Akkoma#11]
Sur Misskey on a une option pour surveiller un post, on est donc notifié des réponses qui lui sont apportées.
On clique sur les 3 petits points sous un post :
![image](https://user-images.githubusercontent.com/20315413/127556042-9c628cfa-b7ac-4799-a64e-a45374df5fec.png)
et on a ce menu qui se déroule avec l'option "surveiller" :
![image](https://user-images.githubusercontent.com/20315413/127555961-acf3e48d-8bc4-4ab4-b9aa-69cb9b757257.png)

C'est super pratique quand on a la même question que quelqu'un par exemple

Ou qu'on veut suivre un débat, échange dans lequel on n'est pas mentionnés.

En attendant, à défaut, je bookmarke et je vais régulièrement voir si y'a des réponses

**Comment by Cl0v1s** [comment]
C'est effectivement une fonctionnalité intéressante. Elle risque de nécessiter un développement coté pleroma, je me documente.
