### ISSUE TITLE
Possibilité de publier en "local seulement"

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/Akkoma#21]
Proposer l'option, lors de la publication d'un message, de l'envoyer en local seulement, c'est à dire à la seule instance bdx.town.

Ce fonctionnement existe sur #GlitchSoc si ça peut aider : https://glitch-soc.github.io/docs/features/local-only-toots/

**Comment by Cl0v1s** [comment]
Lié à https://github.com/Cl0v1s/mangane/issues/21

**Comment by Dehelssey** [comment]
tu as lié le ticket à... lui-même ?
