### ISSUE TITLE
Masquer les réponses

### ISSUE THREAD

**Issue by snan** [Cl0v1s/Akkoma#25]
Sur la timeline de la home, je vois que lorsque les gens répondent à d'autres personnes, je sais comment l'éteindre dans le front-end, mais ce changement n'affecte pas d'autres clients comme Metatext ou simplebot_mastodon 💔

Est-ce déjà possible ?

**Comment by Cl0v1s** [comment]
Bonjour ! 

Je ne suis pas sûr de comprendre ta demande, aurais-tu des captures d'écran pour illustrer ta problématique ? :)

**Comment by snan** [comment]
![IMG_1368](https://user-images.githubusercontent.com/309417/176380426-81484316-123b-4a3a-b8bb-037355862a2d.jpeg)

Les réponses aux autres continuent d'apparaître dans ma chronologie

**Comment by Cl0v1s** [comment]
Merci pour ton screen je comprends mieux ! 

@Dehelssey tu avais le même soucis non ?

**Comment by Cl0v1s** [comment]
A priori c'est effectivement un comportement génant, je vais voir ce que je peux faire !

**Comment by Cl0v1s** [comment]
Après en avoir parlé avec @Dehelssey, on hésite sur le comportement à adopter. 

A priori, ce qui pose problème ici c'est le fait que tu vois des réponses à des toots avec lesquels tu n'as pas interagis.
On pourrait les masquer par défaut, mais certains utilisateurs (dont @Dehelssey et moi-même) apprécions de pouvoir voir les interactions de ce type. 

Tu as parlé d'une option pour les masquer au niveau du front-end, c'est peut être plus au niveau de Metatext ou simplebot_mastodon qu'il faudrait intervenir ? 
Créer une option d'activation/désactivation de ce comportement au niveau du backend ne serait pas très utile: elle ne serait pas activable via les frontend, Il faudrait faire un développement sur Mangane UI et te l'utiliser.

**Comment by snan** [comment]
Le problème est que j'utilise de nombreux clients différents et que beaucoup d'entre eux n'ont pas ce paramètre ; sur Mastodon c'est un réglage (je crois ?). Je n'utilise pas le Soapbox

**Comment by snan** [comment]
C'est déjà une option dans Pleroma-FE et je l'ai là-bas mais cela n'aide pas dans les autres interfaces.

**Comment by Dehelssey** [comment]
Sur mastodon, par défaut, on voit également les réponses des comptes que l'on suit non ? Ça me parait même logique, tous les gens que je suis ne sont pas des "créateurs" de contenu, certain·es se "contentent" de répondre et voir leurs réponses me permet d'interagir à mon tour et de découvrir éventuellement de nouveaux sujets ou comptes.

Cependant, bien que je ne comprends pas la volonté de masquer les réponses pour ne voir que les publications originales, clairement pour moi le blocage doit intervenir côté front pour permettre d'activer ou non ce filtrage.

PS : @Cl0v1s mon problème à moi était que je voyais des réponses à des messages qui m'étaient, eux, inaccessibles. (publications en followers-only de gens que je ne suis pas mais auxquelles des gens que je suis répondent en followers-only aussi)

**Comment by Dehelssey** [comment]
Bon clairement c'est quelque chose qui se gère côté front, que ce soit dans pleroma, soapbox, mangane ou même masto. 

On ne va pas bloquer dans le back l'accès aux réponses et boosts... on ferme ?
