### ISSUE TITLE
Auto-suppression des vieux posts et média après un délai X

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/Akkoma#4]
On peut rendre les publications de l'instance éphémères par défaut, pour ne pas utiliser inutilement du stockage.

Peut-être prévoir une contre-indication pour pouvoir sauvegarder certains messages ? Posts épinglés, posts marqués d'un emoji ou hashtag personnalisé ? Je sais pas ce qui est faisable (je crois avoir compris que certaines instances utilisaient un emoji spécifique pour publier en local seulement par ex)

**Comment by Dehelssey** [comment]
tiens petite piste que m'a filé Amaury ➜ https://lord.re/posts/215-supprimer-ses-vieux-toots-sur-mastodon-ou-pleroma/

**Comment by Cl0v1s** [comment]
J'attends de voir l'évolution de la quantité de données. Pour l'instant on est loin d'avoir un soucis avec seulement 30% de l'usage du disque, essentiellement occupés par les sauvegardes en attente de rapatriement sur un autre disque. 

Mais je garde sous le coude si besoin !

**Comment by Dehelssey** [comment]
😯
